/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';
  static const String? _kFontPkg = null;

  static const IconData airport_shuttle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flight_takeoff = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healing = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_cafe = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_car_wash = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pets = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tram = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_dining = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xf007, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rouble = IconData(0xf158, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_basket = IconData(0xf291, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData piggy_bank = IconData(0xf4d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tshirt = IconData(0xf553, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
